### ISSUE TITLE
Invalid hostname

### ISSUE THREAD

**Issue by ghost** [kevinle-1/Windows-Telemetry-Blocklist#2]
telemetry.appex.bing.net:443
Invalid hostaname, list successfully retrieved.

Just fyi :)

**Comment by n0svc** [comment]
Confirmed. Was going to report that also.

      [i] Analyzed 161 domains, 1 domains invalid!
      Sample of invalid domains:
      - telemetry.appex.bing.net:443

**Comment by kevle1** [comment]
Sorry for the (extremely) late reply! Updated :)
